NumberOfParameters: 3
MPCMotionParameters_1:
  base_velocity: [0.0, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: 0.0
  motion_mode: 2
  duration_ms: 3000
MPCMotionParameters_2:
  base_velocity: [0.7, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: 0.0
  motion_mode: 2
  duration_ms: 7000
MPCMotionParameters_3:
  base_velocity: [0.0, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: 0.0
  motion_mode: 2
  duration_ms: 3000
