NumberOfParameters: 4
MPCMotionParameters_1:
  base_velocity: [0.0, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: 0.0
  motion_mode: 2
  duration_ms: 3000
MPCMotionParameters_2:
  base_velocity: [0.4, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: 0.4
  motion_mode: 2
  duration_ms: 15708
MPCMotionParameters_3:
  base_velocity: [0.4, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: -0.4
  motion_mode: 2
  duration_ms: 15708
MPCMotionParameters_4:
  base_velocity: [0.0, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: 0.0
  motion_mode: 2
  duration_ms: 3000
