NumberOfParameters: 4
MPCMotionParameters_1:
  base_velocity: [0.0, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: 0.0
  motion_mode: 2
  duration_ms: 3000
MPCMotionParameters_2:
  base_velocity: [0.2, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: 0.3
  motion_mode: 2
  duration_ms: 10472
MPCMotionParameters_3:
  base_velocity: [0.2, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: -0.3
  motion_mode: 2
  duration_ms: 10472
MPCMotionParameters_4:
  base_velocity: [0.0, 0.0]
  base_position: [0.0, 0.0]
  base_angular_velocity: 0.0
  motion_mode: 2
  duration_ms: 3000
