set(CONTROLLER_MPC_HOTSTARTING_ENABLED         OFF          CACHE BOOL   "")
set(CONTROLLER_LOGGING_ENABLED                 OFF          CACHE BOOL   "")
set(CONTROLLER_HUMOTO_MPC_SOLVER_NAMESPACE     "quadprogpp" CACHE STRING "")
set(CONTROLLER_HUMOTO_IK_SOLVER_NAMESPACE      "kktsolver"  CACHE STRING "")
