set(CONTROLLER_HOTSTARTING_ENABLED         OFF          CACHE BOOL   "")
set(CONTROLLER_LOGGING_ENABLED             OFF          CACHE BOOL   "")
set(CONTROLLER_HUMOTO_MPC_SOLVER_NAMESPACE "quadprogpp" CACHE STRING "")
